Document: gbterminal
Title: Debian gbterminal Manual
Author: <insert document author here>
Abstract: This manual describes what gbterminal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gbterminal/gbterminal.sgml.gz

Format: postscript
Files: /usr/share/doc/gbterminal/gbterminal.ps.gz

Format: text
Files: /usr/share/doc/gbterminal/gbterminal.text.gz

Format: HTML
Index: /usr/share/doc/gbterminal/html/index.html
Files: /usr/share/doc/gbterminal/html/*.html
