#!/bin/sh

set -e

case "${1}" in
	configure)
		update-alternatives --install /usr/bin/x-terminal-emulator \
			x-terminal-emulator /usr/bin/gbTerminal 40 \
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

# Automatically added by dh_installmenu
if [ "$1" = "configure" ] && [ -x "`which update-menus 2>/dev/null`" ]; then
	update-menus
fi
# End automatically added section


exit 0
