#!/bin/sh
# postrm script for gbterminal

set -e

case "$1" in
    purge|remove|disappear)
        update-alternatives --remove x-terminal-emulator /usr/bin/gbterminal | exit 0
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac



exit 0
