' Gambas module file

' Innova Project 
' Copyright © Asociación Civil Edulibre
' Info@edulibre.com
'
' Jorge Recinos - Developer
' jrecinosd@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Private cone As New Connection


Public Sub Main()
  
   
  
End

Public Sub Set_NewUser(Aplicacion As String)
  
  EdulibCap.lbl_user.Text = Aplicacion & Day(Now) & Month(Now) & Year(Now) & Hour(Now) & Minute(Now) & Second(Now)
  
End


Public Sub Set_Log(Nivel As String, Grado As String, Materia As String, Contenido As String, Accion As String, Usuario As String, Actividad As String)
  Dim insert As String
  
  Contenido = M_Busqueda.RemoveChar(Contenido, "'")
  
   insert = "INSERT INTO tbl_log (nivel, grado, materia, contenido, accion, usuario, fecha_hora, id_actividad) VALUES ('" &
              Nivel & "','" & Grado & "','" & Materia & "','" & Contenido & "','" & Accion & "','" & Usuario & "',datetime('now','localtime'),'" & Actividad & "')"

    
    cone = MDB_Connection.Conectar()
    cone.Exec(insert)
    MDB_Connection.Desconectar(cone)
End


