' Gambas module file

' Innova Project 
' Copyright © Asociación Civil Edulibre
' Info@edulibre.com
'
' Jorge Recinos - Developer
' jrecinosd@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Public $con As Connection

Public Procedure Conectar() As Connection
    $con = New Connection
    Try $con.Close()             ' Cierra la conexion el try permite falle sin error
    $con.Type = "sqlite3"        ' Define el tipo de Conexion
    $con.Host = (Application.path &/ "DB/") ' Host sera la ruta en donde esta el archivo de la db sqlite
    $con.Name = "edulibcap.db"    ' nombre de la base de datos es el nombre del archivo base de datos
    $con.Open()                  ' Activamos y Abrimos la conexion, el try es para que permita un error
  
    'Print "Conectado? : " & $con.Opened ' Devolvera TRUE o FALSE segun si "try $con.Open()" fue exitoso en "conectarodbc()"
  
    Return $con
End

Public Sub Desconectar($con As Connection)
  
  $con.Close
  $con = Null
  
End

