' Gambas module file

' Gambas class file

' Innova Project 
' Copyright (C) Herberth Guzmán
' herberthguzman@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Public Sub Init_00()
  
  Component.Load("gb.desktop.x11")
  
  If Not Exist(Desktop.ConfigDir &/ "Innova/Innova_Config.conf") Then
    M_Init_.Init_Value
  Endif
  Init_01
  
End

Public Sub Init_01()
  
  M_Theme.IconTheme
  Init_02
  Wait 0.2
  
End

Public Sub Init_02()
  
  M_Theme.Show_Theme
  Init_03
  Wait 0.2
  
End

Public Sub Init_03()
  
  Application.Env["APPMENU_DISPLAY_BOTH"] = "1"
  f_settings.Show
  
End
