' Gambas module file

' Gambas class file

' Innova Project 
' Copyright (C) Herberth Guzmán
' herberthguzman@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Const ENCODING As String = "Encoding=UTF-8"
Public splash_update As String 
Public splash_show As String 
Public logo_start As String 
Public iSize_Panel As Integer = 28 '  
Public IconSize_Panel As Integer = 48 
Public iSize_Large_Panel As Integer = 100 
Public sPosition_Panel As String = "Bottom" 

Public IconSize_Desktop As Integer = 48 
Public IconSize_Innova As Integer = 48 
Public IconSize_Launcher As Integer = 48 
Public iDesktop As Integer = 4
Public sOrganize As String = "Rows"
Public sOrder As String = "Name"
Public iOpacity_Launcher As Integer = 100 
Public iOpacity_Panel As Integer = 100 
Public IconLine_Desktop As Integer = 1 
Public sLang As String = ((Left(System.Language, 2)))

Public mytheme_icons As String
Public sLang_Select As String 
Public spath_pic_user As String 
Public ipanel_size As Integer 
Public sPanel_Position As String
Public sImage_Panel_Systray As Image 
Public sImage_Panel_Systray1 As String 
Public Group_Cat As String 

Public aDir As New String[]
Public sDir As String 
Public sName_Font As String = "Roboto_Light"
Public iSize_Font As Integer = 9
Public iSize_Icons_View As Integer = 48
Public iSize_Icons_Grid As Integer = 30
