' Gambas module file

' Gambas class file

' Innova Project 
' Copyright (C) Herberth Guzmán
' herberthguzman@gmail.com
'
' This program is free software; you can redistribute it and/or modify
' it under the terms of the GNU General Public License as published by
' the Free Software Foundation; either version 2 of the License, or
' (at your option) any later version.
'
' This program is distributed in the hope that it will be useful,
' but WITHOUT ANY WARRANTY; without even the implied warranty of
' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
' GNU General Public License for more details.
'
' You should have received a copy of the GNU General Public License
' along with this program; if not, write to the Free Software
' Foundation, Inc., 51 Franklin St, Fifth Floor,
' Boston, MA  02110-1301  USA

' Homepage: http://http://sourceforge.net/projects/innovadesktop

Public ruta As String
Public font_theme As String
Public colors_theme As String

Public Theme_Gtk As String 
Public Lang_System As String
Public Settings_Core_Innova As New Settings(User.Home &/ ".config/Innova/Innova_Config.conf")

Public Sub Theme_Application()
  
  Dim sResult_Lang As String 
  Dim sResult_Theme As String 
  
  Try sResult_Lang = Settings_Core_Innova["Language/Language_System"]
  Try sResult_Theme = Settings_Core_Innova["Style_Desktop/Theme_Name_Icons"]
  
  Theme_Gtk = sResult_Theme
  Lang_System = sResult_Lang
  Application.Theme = Theme_Gtk
  
  'Catch
  '  Debug "ERROR [ " & DConv(Error.Text) & " ]"
  
End

Public Function Show_Theme()
  
  Dim ctrl As Control
  Dim Settings_Config_Theme As Settings
  Dim sPath_Theme As String
  Dim sColor As String
  Dim sFont_Name As String
  Dim iFont_Size As Integer
  Dim sResult_Trans As String 
  Dim sResult_Img_Launcher As String 
  
  Dim sResult_Font_Name As String 
  Dim iResult_Font_Size As Integer
  Dim sResult_Font_Color As String 
  Dim sResult_Img_Look As String
  
  Dim sDir As String
  Dim sResultTheme As String
  Dim sPath As String
  
  Dim sResult_Inn_WallpaperImg As String 
  Dim sResult_Inn_BackgroundImg As String 
  Dim sResult_Inn_HorizontalPanelImg As String 
  Dim sResult_Inn_VerticalPanelImg As String 
  Dim sResult_Inn_SearchImg As String 
  Dim sResult_Inn_LogoImg As String 
  Dim sResult_Inn_LauncherImg As String 
  Dim sResult_Inn_Font_Color As String 
  Dim sResult_Inn_Font_Name As String 
  Dim iResult_Inn_Font_Size As String 
  Dim sResult_Inn_Logo_Img_Dist As String 
  Dim sResult_Inn_Panel_Img As String 
  Dim sResult_Inn_Launcher_Type As String 
  Dim sResult_Inn_Look_Img As String 
  
  Settings_Core_Innova.Reload()
  For Each sDir In ["/usr/share/Innova/Theme/", Desktop.ConfigDir &/ "Innova/Theme/"]
    Try sResultTheme = Settings_Core_Innova["Style_Desktop/Theme_Name_Innova"]
    
    '  Print sResultTheme
  Next
  
  sPath = sDir & sResultTheme &/ sResultTheme & ".Inn"
  Settings_Config_Theme = New Settings(sPath)
  sPath_Theme = File.Dir(sPath) 
  
  Try sResult_Trans = Settings_Core_Innova["Innova/Transparent"]
  Try sResult_Font_Color = Settings_Core_Innova["Style_Desktop/Font_Color"]
  Try iResult_Font_Size = Settings_Core_Innova["Style_Desktop/Font_Size"]
  Try sResult_Font_Name = Settings_Core_Innova["Style_Desktop/Font_Name"]
  
  Try sResult_Img_Launcher = Settings_Config_Theme["Meta_Theme/Inn_Background_Img"] 
  Try sResult_Img_Look = Settings_Config_Theme["Meta_Theme/Inn_Look_Img"]
  
  ''reaser nuevo
  ' Try sResult_Wallpaper = Settings_Config_Theme["Meta_Theme/Inn_Wallpaper_Img"]
  'Try sResult_Panel = Settings_Config_Theme["Meta_Theme/Inn_Panel_Img"]
  
  sResult_Inn_WallpaperImg = Settings_Config_Theme["Meta_Theme/Inn_Wallpaper_Img"]
  sResult_Inn_BackgroundImg = Settings_Config_Theme["Meta_Theme/Inn_Background_Img"]
  sResult_Inn_HorizontalPanelImg = Settings_Config_Theme["Meta_Theme/Inn_Hor_PLauncher_Img"]
  sResult_Inn_VerticalPanelImg = Settings_Config_Theme["Meta_Theme/Inn_Ver_PLauncher_Img"]
  sResult_Inn_SearchImg = Settings_Config_Theme["Meta_Theme/Inn_Search_Img"]
  sResult_Inn_LogoImg = Settings_Config_Theme["Meta_Theme/Inn_Logo_Img"]
  sResult_Inn_LauncherImg = Settings_Config_Theme["Meta_Theme/Inn_Launcher_Img"]
  sResult_Inn_Font_Color = Settings_Config_Theme["Meta_Theme/Inn_Font_Color"]
  sResult_Inn_Font_Name = Settings_Config_Theme["Meta_Theme/Inn_Font_Name"]
  iResult_Inn_Font_Size = Settings_Config_Theme["Meta_Theme/Inn_Font_Size"]
  sResult_Inn_Logo_Img_Dist = Settings_Config_Theme["Meta_Theme/Inn_Logo_Img_Dist"]
  sResult_Inn_Panel_Img = Settings_Config_Theme["Meta_Theme/Inn_Panel_Img"]
  sResult_Inn_Launcher_Type = Settings_Config_Theme["Meta_Theme/Inn_Launcher_Type"]
  sResult_Inn_Look_Img = Settings_Config_Theme["Meta_Theme/Inn_Look_Img"]
  
  If sResultTheme Then
    
    ''FRM_TRANS
    If sResult_Trans = "1" Then
      f_PC_Info.Transparent = True
    Endif
    
    ''IMG_BACKGROUND    
    
    f_PC_Info.Picture = Picture[sPath_Theme &/ sResult_Inn_Look_Img]
    
    If Not IsNull(sResult_Font_Color) Then
      sColor = (sResult_Inn_Font_Color)
      
      For Each ctrl In f_PC_Info.Controls
        '' Try ctrl.Foreground = Val(sColor) 
        f_PC_Info.pnlIconsCPU.Foreground = Val(sColor) 
        f_PC_Info.pnlIconsMemory.Foreground = Val(sColor) 
        f_PC_Info.pnlIconsHD.Foreground = Val(sColor) 
        
        f_PC_Info.pnlIconsSO.Foreground = Val(sColor) 
        f_PC_Info.pnlIconsDE.Foreground = Val(sColor) 
        f_PC_Info.pnlIconsGraphics.Foreground = Val(sColor) 
        
      Next
    Else
      f_PC_Info.ipnPCInfo.Foreground = Color.Black
    Endif
    
    If IsNull(sResult_Inn_Font_Color) Then
      sColor = (sResult_Font_Color)
      
      For Each ctrl In f_PC_Info.Controls
        Try ctrl.Foreground = Val(sColor) 
        
      Next
      
    Endif
    
    ''NAME_FONT
    
    If IsNull(sResult_Font_Name) Then
      sFont_Name = (sResult_Inn_Font_Name)
      
      For Each ctrl In f_PC_Info.Controls
        ctrl.Font.Name = (sFont_Name) 
      Next
      
    Endif
    
    If Not IsNull(sResult_Inn_Font_Name) Then
      sFont_Name = (sResult_Font_Name)
      
      For Each ctrl In f_PC_Info.Controls
        Try ctrl.Font.Name = (sFont_Name) 
        
      Next
      
    Endif
    
    ''SIZE_FONT
    
    If IsNull(iResult_Font_Size) Then
      iFont_Size = (iResult_Inn_Font_Size)
      
      For Each ctrl In f_PC_Info.Controls
        ctrl.Font.Size = (iFont_Size) 
      Next
      
    Endif 
    
    If Not IsNull(iResult_Inn_Font_Size) Then
      Try iFont_Size = Val(iResult_Font_Size)
      
      For Each ctrl In f_PC_Info.Controls
        Try ctrl.Font.Size = (iFont_Size) 
      Next
      
    Endif
    
  Endif
  
  ' M_DB.Close(cx)
  
  'Catch
  ' Debug "ERROR [ " & DConv(Error.Text) & " ]"
  
End
